{{ range .Values.deployments.servicelist }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fsgbutruesaaschart.fullname" $ }}-{{ .service }}
  namespace: {{ .namespace }}
  labels:
{{ include "fsgbutruesaaschart.labels" $ | indent 4 }}
spec:
  type: {{ $.Values.service.type }}
  ports:
    - port: {{ $.Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "fsgbutruesaaschart.name" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app: {{ .labels.app }}
    slot: {{ .labels.slot }}

---
{{end}}

