{{ range .Values.deployments.servicelist }}
{{- if eq .labels.slot "blue" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mychart.fullname" $ }}-{{ .service }}-blue
  labels:
{{ include "mychart.labels" $ | indent 4 }}
spec:
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "mychart.name" $ }}
      app.kubernetes.io/instance: {{ $.Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "mychart.name" $ }}
        app.kubernetes.io/instance: {{ $.Release.Name }}
        app: {{ .labels.app }}
        slot: blue
    spec:
    {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      tolerations:
        - key: node.kubernetes.io/not-ready
          effect: NoExecute
          tolerationSeconds: 0
        - key: node.kubernetes.io/unreachable
          effect: NoExecute
          tolerationSeconds: 0
      containers:
        - name: {{ $.Chart.Name }}
          image: "{{ .image }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            {{- if eq .service "company" }}
            {{- toYaml $.Values.resources | nindent 12 }}
            {{- else }}
            {{- toYaml .resources | nindent 12 }}
            {{- end }}
      #nodeSelector:
        #{{ $.Release.Namespace }}: "true"
    {{- with $.Values.affinity }}
      affinity:
        {{- toYaml $ | nindent 8 }}
    {{- end }}
---
{{- end }}
{{end}}
