{{ range .Values.deployments.servicelist }}
{{- if eq .labels.slot "blue" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mychart.fullname" $ }}-{{ .service }}-prod
  labels:
{{ include "mychart.labels" $ | indent 4 }}
spec:
  type: {{ $.Values.service.type }}
  ports:
    - port: {{ $.Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "mychart.name" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app: {{ .labels.app }}
    slot: {{ .labels.slot }}

---
{{- end }}
{{end}}

